language: java
services:
  - docker
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2
install: true
jobs:
  include:
    - stage: build
      name: "Build - OpenJDK 8"
      script: mvn -B verify
      jdk: openjdk8
    - stage: build
      name: "Build - OpenJDK 11"
      script: mvn -B verify
      jdk: openjdk11
    - stage: deploy
      name: "Deploy doc"
      if: type != pull_request AND branch = master
      script: ./deploy-doc.sh
